import React from "react";






export default function BookMovie() {
  return (
    <div className="feature-section padding-top-20 padding-bottom-5 container" style={{background: '#22272b', maxWidth: '100% !important', overflowX: 'auto'}}>
  <div className="list-seat" style={{margin: '0 auto', width: 810, position: 'relative', height: 'auto'}}>
    <div className="screen-thumb">
      <h4 className="screen">Màn hình</h4>
      <img src="http://pixner.net/boleto/demo/assets/images/movie/screen-thumb.png" alt="movie" />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654941,'zHi3DyjGUg5Iki4s7LDD2kkZJVzwWPNZq18lJcslEPI=','0','B')">B01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654950,'7OskxQ73C0ZSqJ0YaIb9utnGYB17adi0dN+5GR/xs7U=','0','B')">B02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654958,'hsQKsUEtY3qBKlshn5OjTfL/XBlKiB0gOuRpTwHeImU=','0','B')">B03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654967,'FoLUPR38gEWVntdqIfmDjSEUbvCTMFSs6V3oxgOOg2o=','0','B')">B04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654975,'hGZwaRZqoVxyFuY92VUcq2J6hF3ZNb/6sN7WpJj4En4=','0','B')">B05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654984,'FtDBwhGmQGU2yiRP/iXd3AXoIK2zV/D9AtLuckFttwQ=','0','B')">B06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654992,'kHMpOB3Xmts43aBQ4nWsdXEZRKJzho0k8U1QBzgTUgI=','0','B')">B07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655002,'vq7dHzkz2YySnREo/AsYVAZiaPHUfBzk8qylm9fgxrI=','0','B')">B08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655029,'R6FyHx4L95aCxolE7MA43fAarH7l8GsDp+ews3U+4Ro=','0','B')">B09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655038,'FDNQebpVx1Fyma5JkGQCAkCMgy41huEy9evz5SPcdIQ=','0','B')">B10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655046,'LHvsjMXhTyMU/AhpHDSdo84PQgIQQCkSjiYfBovgRts=','0','B')">B11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655055,'TWtIscQtl8qXOy6uvbZqTBNlNgolUltq57+b8YGcFbo=','0','B')">B12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655063,'VjhcWdiyEjwJtiNwiYPJCjRGpyAYcMZfgC0NRKs+kVo=','0','B')">B13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655072,'kyIjprY4ujZxrwT/1TT6L3wk4grW6FbnmSgLBuMg0z4=','0','B')">B14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655080,'JtHInuqmEuR8lr5Iy7l/Ic1dLm78V44qP2i8GJF60KM=','0','B')">B15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655089,'TpNriDvoVO0nYfOPt+JLoXGJXbQlT8lfRX1dORm1e3U=','0','B')">B16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655009,'TIRA3qlIajjdAt1xxTZFjbj5EX4+bSaceaoZyAJZFm8=','0','B')">B17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654942,'M1EVL4KAfR8Q2uKfF8D4fKOea+wd6aPpdXuojHy/jZk=','0','C')">C01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654951,'j5IYW6DfaV4/DA4IahXQxtpHw0510XKxzUbSNxysUEY=','0','C')">C02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654959,'uTUrbadU5nLVjfN3JLdJowKTDRvgJGaom2xoxeDKFfw=','0','C')">C03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654968,'lsOX0glPlPYd3jJT8LYsjUQAzH9lq0SasBEkPb2thwE=','0','C')">C04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654976,'OYSGcR3H86OaD0I2ALqwpmSl47PtZ7cqboD4ui62ERw=','0','C')">C05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654985,'DpTK131DX+8jnacjqCZlILG1iGkxIVBI96So8I4UhlI=','0','C')">C06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654993,'gplH4hDtyN0iPGGdJGH2k8x/xZpj1T9dVYWLTaWsE+Y=','0','C')">C07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655003,'pr3LbjhKFpLhrdzZqRLrK4cvKcQMf/SfV+mypEH55C8=','0','C')">C08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655030,'zRZS2UBGoPa2saKMNXBci9XDIQMDghIXVrtWIrGjNtM=','0','C')">C09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655039,'vgu3eacRpJtPtjyDcOLDR+mg2csp5p14XeEv8H/UBD8=','0','C')">C10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655047,'TTtxrrB30r1ugzWT/Hg2o6/3sOS7yo7pcCsB7Vl7jsU=','0','C')">C11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655056,'qU4kpGfayKiA4SwYxnVeR4yuDpeVxqMNkDWwp7AEvL0=','0','C')">C12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655064,'WpBN09DGVbQuETRx0QQ2wamb3DUD+6cvt+O9Sa8q4zI=','0','C')">C13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655073,'Eg1V3U2mZLlm9nBjPack2yMMlmYt2FhvP/n4BzKJkC0=','0','C')">C14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655081,'lkWdorzu9WQVIK2IxZC/9yVNGHXYlurFzYmz7Nbw98s=','0','C')">C15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655090,'16GW41EPboL0eQld/ZdHFc5rhF8IquaPfVD24oAVpV0=','0','C')">C16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655010,'H6WBYpmtcUKpkGCGiUl78FxDbjWcKw05tcqjUFKgH60=','0','C')">C17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654943,'Rrjpij61RDyndjcCOBnjXB8cDhYbJNfr4MFkME7jT6o=','0','D')">D01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654952,'sWFe4VawY+8WriSzZbE4lMqttUDSyLSaULl1uu0oYeQ=','0','D')">D02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654960,'ES+c75sRdb7WEmsQgPs4TiU2X/fuWvyrNf5akduJ+AM=','0','D')">D03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654969,'Oq1Igo3rJicUcIlN08TsqKgqJHaicN7MnWU4UVwHowk=','0','D')">D04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654977,'Dz872DFQewM+YvbojVNwK6npSWloPLCX9VIKt/UrpR4=','0','D')">D05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654986,'n7Cv5I1zHcR7NJM3bPL3o/Uy8oGqoMP/igeyzFewTxM=','0','D')">D06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654994,'cqCZI0C0ChB/vJnnWhk7jy79IIfQIEj2zhmImc4LhBk=','0','D')">D07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655004,'Pu1yLP03EQx4ZRBhgtDqWGMb02aQOB03MKU+mYTrzn8=','0','D')">D08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655031,'C/RW96qUe9I1U+xelcv2X0kLl8rbwz0IiJHkdIdkQJc=','0','D')">D09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655040,'WYSyb3S27V2d8tzjWNfhYKT7Ks5FKWhmuHwtwrLFaaQ=','0','D')">D10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655048,'d+J5+MK3mmHtpN8xHLkWVxgXcj32OJrQu2PAscUkx3o=','0','D')">D11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655057,'LW4vDcl/hM5ZlHVsgvbbSj/uWHZ07D6J2h+yHGNL8mc=','0','D')">D12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655065,'ZQzC1UtTIXij/iqDgVuAG3Msj3kLtXjVGKQUh2Q/szo=','0','D')">D13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655074,'mYh6E8Cn7+61DjkobWyyuqew8TRhbZow23Z9MXFKWaw=','0','D')">D14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655082,'ODXyawdY6RVe2xlpO4aQ9qbjobeZ3m5lfg3VMBn2+Bo=','0','D')">D15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655091,'pZfKcHSr+IIRBSeCqSPI2YTwmJU5tIXO65yYAHYHAxQ=','0','D')">D16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655011,'EiX/KRpqm+Ce6YIHibLm86Rpdxd57PtWr2OxdvEYe8Y=','0','D')">D17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654944,'6gjTM5JD9POVQSz5vQOOBw0vnfrY/XiMQK5UyR2p9Co=','0','E')">E01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654953,'4uHNH5DM2ETBAzAztM3CnFbZhR2mHWNyGH4EuaGELO4=','0','E')">E02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654961,'HPg57ZWpjYchZwf+EcwtxykuIH266xe7GAuLq7cmkjk=','0','E')">E03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654970,'t6ymSmfvUmjtJ9ck3b86YQlorBmaWsh6zPhsWLNpCPM=','0','E')">E04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654978,'dtvxGT4d592HjtPxvPxuKAZZWA3emhazJhlDqcC8RZQ=','0','E')">E05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654987,'1JR03v4P90Rn6J7TGfDEHyQmAt4zglK7IlZ6cah1ltA=','0','E')">E06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654995,'u/MoIQSUH1X7VYaLsKO+hBMibT7IrVpw64eaGlp9oGE=','0','E')">E07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655024,'WygcVsNeNqc84vuPW+MI5lexH5IPZKgQhExEJg5m2Fg=','0','E')">E08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655032,'XwAAzxWYBJ3fRK5YcbAd/5aVxHjzC6VEEYKHsHBVMxg=','0','E')" className>E09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655041,'yHV7lH5uOAS8H9+mgwvwGg3SzaKI5HVkBXSYIbZQiCs=','0','E')" className>E10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655049,'xqCbCRFH9XD3qyN/Z0grGInmVv5I8VD1iTFslgreueQ=','0','E')" className>E11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655058,'5RMPKUyMbOjbHvm3mECJGvW8abas909/9AFuXDx/7IA=','0','E')">E12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655066,'efUr6loIrMzGEoUdmIx8fwcN9XuWYvOFL0YpNSJ/uTk=','0','E')">E13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655075,'PJ7KYiW4LQo6c/xdsB2c+rA6R5tAFmvSnfhId86pTdU=','0','E')">E14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655083,'XxANGgIP2/QucJeL23xrWPlt2afxslQ1mhnSBT9OVv0=','0','E')">E15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655092,'7kpLci9tuAKv2NwLXjZ098HM0TRYXwoMGj5hcYoEbOk=','0','E')">E16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655012,'L+QR6XuyJRoDAPGbceLGBCoHPqyY4GzRCpGw2A1uzzk=','0','E')">E17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654945,'ReLIUbrbRXNRpO/vEf6dAt6RLt2Sp1J8Rik3DXZTUjQ=','0','F')">F01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654954,'o+/seJZ1w50EYDCCVlwJBEoOd9gCiRb4ZV4OfLESY0o=','0','F')">F02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654962,'RjXLNXnQbX1EXldHQJT1e5QE2I6IrFMJaIlOK2wvtJY=','0','F')">F03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654971,'teK5m3R1qyOV27HRzSY7BADCmX65+sg93b808LJP/K8=','0','F')">F04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654979,'Xim483DVRaPkwpZwM4baWnM4NVHMdgoHIeAkKw2mvDk=','0','F')">F05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654988,'o7g5FRSQkhq9jLkYRt48LrQ8XMzDDzsJdfuyz65lhsc=','0','F')">F06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654996,'HX1B1zjvea8uimMHSYehrwUUqcQAkZN7wyXTYiw1SwQ=','0','F')">F07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>F08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>F09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>F10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655050,'VIl7FuYWE7+qawrBqDXLmx/xhNtAwmER+nBNwxBc3UY=','0','F')" className>F11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655059,'mhXWZrfclQguxGOcBhzqZ69DbVWkOHhoPAhGykUSlmg=','0','F')">F12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655067,'UpXfE2emK6K7tn9bw8Qckd/KLP/vk5irbNgVRYaXiLA=','0','F')">F13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655076,'4lPgWTWZGpp76jwI9ZdqTmK2tOmyFfSz4fi0xXzeqiI=','0','F')">F14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655084,'3wRNp1Mo/1DUOSxbQAl7dMNcNu81WsOBCNTm9+SZYI8=','0','F')">F15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655005,'IgNBgrrqLo6rCo4RweYV6eMvsV0zkjKmuQlZEzS5C20=','0','F')">F16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655013,'l62AU6B9cOqWjPXoje6NwhPmBvbJgUr6Tz2hxkReKX0=','0','F')">F17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654946,'BKY5sjcIvlPIk/bzrFs/r9ST7bW1LZpt/uG5zUDeFOw=','0','G')">G01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654955,'0bmwh+bDsLs7x1sGxbSfhDKP5bKa2A17EniT6S5bY4I=','0','G')">G02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654963,'PuOiou9u4KolDubK9PF1E+2K1vPVZFDRVoi7pWG3nOA=','0','G')">G03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654972,'2m124oNJGZ8sOIcSzRiOYhK4J8yDhiOnJs5V8mBqihM=','0','G')">G04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>G11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655060,'hcc5huyjr3/dNJnG5CWI/atgy1Jw8nZ0qR5d92F4AEw=','0','G')" className>G12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655068,'n03FnicqIISacHg++etlTWqGmhBpW4wshpXIY7DuYh4=','0','G')">G13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655077,'Ar/Bt5qOsZFvRtuxETKp9GORo919965PUjTh3LXgytg=','0','G')">G14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655085,'qUXkLH2Je/k1bae/IajHSLmACdqJ5r0nWEUS7d7f1T8=','0','G')">G15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655006,'Y+CYQU07zgay/5qgQDfd7vG5JCnrolIIW1qLPFDxnG4=','0','G')">G16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655014,'qyDZTFuC42c0eFc8VZW7qLUNuITyCsdVUWVzrx3BuhU=','0','G')">G17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654947,'2vNZflunCPbdbxcjLgJuKgej5NP9PpTzUKP1NHnuDqA=','0','H')">H01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654956,'RTFUBEd1nwXUT4kQgnBzyfC5ZTrMNeTE4YLyPU8Vcw4=','0','H')">H02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654964,'s01hj18Nva68CQPvA33pDhL4QNobJ0fR/z8o29KArkY=','0','H')">H03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>H10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655052,'tQKzKQ/pQUeqro3ZGYW+rE6wLUwMTXSsbKjPFVFB0Fc=','0','H')">H11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655061,'xXWgcXblGYUgo77o7HBXSmJr6hx6ymP+wPNbw2RMwvU=','0','H')" className>H12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655069,'UQkSDhA4LtiZi5hhY8naWaglUarDBs3ioIxUTtW4SCU=','0','H')">H13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655078,'9CXk4HYmG6uLWPR/1Kx0H3KczvPy1gzx9mF10e68ZJ0=','0','H')">H14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655086,'lUdp/kgM79q0GepTyOxiL69UnUUi3td3pyoM9+Hufc0=','0','H')">H15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655007,'eEWzt+awVGICwd3kbGU1Ht4Y2mZAYvlEAGX4sTlv2I0=','0','H')">H16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655015,'GFpXPyB3DfvfX1vCsfPFPXvaZfbuJKqchPEof9t7Dr8=','0','H')">H17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654948,'3+JJ0ezqeSlnNOGKGE/020RSYEym1sYMF7m5ggrJmJc=','0','I')">I01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654957,'Ug9ue7beSVdZ1+U9qNNL9t5+4Mz5/pQeSL8oLt+jJCc=','0','I')">I02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654965,'UOYH815uwv/+DTsIcvCzCYAPX/7kVWgK3XnTHcfHadI=','0','I')">I03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654974,'QoL1e4U0IHTvzuhGiQiOL6mjcHb6gJx0TqpnsdOaUA0=','0','I')">I04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654982,'i9dfLt5f7nVg9/rNvbP1mGQd7pPXhAY1VAp15JUBr3w=','0','I')">I05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654991,'sXfhcMh0pEjIviJQy050A1tckoKSvxdg70Lt6DUrK9A=','0','I')">I06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203654999,'u/C7soHDiEcpMhKt4w62afcqSR3tDuOGnUVrE2CQDfQ=','0','I')">I07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655028,'57JW/0mR1hGMBKws56nSGudXoZeFqlBBkdhT2Bak4iM=','0','I')">I08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655036,'uJrFoZPD1GWll84QNj5g0p58x+HSP1w52yaYLAnZnyM=','0','I')">I09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655045,'9d4KdbTtK0H6oWUD2CAB/8NlHNyPD/LMmeohobSy07Q=','0','I')">I10</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655053,'24jBM2tavXe+kFUOVy5vjvL83pv4hZFJ2a1+FOR46ok=','0','I')">I11</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655062,'8xMuRwXXb2D8h1tnAxP7mjDCFkfKX6Uoq5XgAZay+A0=','0','I')">I12</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655070,'XNlN5WexgWox4FgdsltpznsysLWfChrHwNKKH4SIkhw=','0','I')">I13</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655079,'YAmioZ806w4Ev4pT73uSESBoLZWvTkSwmLZ8NBtGIvE=','0','I')">I14</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655087,'ZZfkFgG7BOj7TYVzElaBWLLpQIQF7rYT/lu8eueKtVg=','0','I')">I15</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655008,'2GHxcFnwvQd+5oe208yr9wC/UHRd6Pb7OxRoYyJ3FXw=','0','I')">I16</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-standard.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} onclick="onClickSelect(this,1203655016,'FdxTkDVJSJQrGHTu7IttGKfaFQd+E5Sc35JqlNDESx8=','0','I')">I17</p>
      <p style={{margin: 3, width: 35, height: 35, backgroundColor: 'transparent'}} />
    </div>
    <div className="clearfix row" style={{position: 'relative', display: 'flex', justifyContent: 'center'}}>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203654949" onclick="onClickSelect(this,1203654949,'Xs3j/PEEP8Gp0uyntIUCkcLIg9ImzXp2Rw2MITAGexc=','swbox1203654949','J')">J01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203654949" onclick="onClickSelect(this,1203654949,'MXyUTP0lA/cdzkaV6OkLWuTnOXYNAKCxiHatS/928GM=','swbox1203654949','J')">J01</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203654966" onclick="onClickSelect(this,1203654966,'P4sb9mWsMtTQPEFTop8Mv1yq7JkbCHfMrQMezAfDnkw=','swbox1203654966','J')">J02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203654966" onclick="onClickSelect(this,1203654966,'4kzcDdj2s9QGsHICC0LH7iDK21a4HrGVyUlK2CI75b4=','swbox1203654966','J')">J02</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>J03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>J03</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655000" onclick="onClickSelect(this,1203655000,'2HyRE09ULwXeeA7fLGQLbfi56ghV47ttH1eOps3fN1o=','swbox1203655000','J')">J04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655000" onclick="onClickSelect(this,1203655000,'tjS0msUlkxBlJldSDa2uMmCSicErLH6p1T0QC3cTNAM=','swbox1203655000','J')">J04</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655037" onclick="onClickSelect(this,1203655037,'Aj8AwRfIxsy55zYwluMuWwdjnUEuCDPXJBnF9gxBZbk=','swbox1203655037','J')">J05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655037" onclick="onClickSelect(this,1203655037,'gu3Cak5wILzL6860pOlSWrpA5q8MHMFBLz6odHf5hmY=','swbox1203655037','J')">J05</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655054" onclick="onClickSelect(this,1203655054,'Kie7zkgPjRShEOFHZ+eOCSiqiA2Glpog/BfXl7tAxbU=','swbox1203655054','J')">J06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655054" onclick="onClickSelect(this,1203655054,'I/v1+2v2+LnjnEpEs2vt5F0Nu1RzafC7pUMiNe3Kvm0=','swbox1203655054','J')">J06</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>J07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}}>J07</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655088" onclick="onClickSelect(this,1203655088,'mEjZXNUgvdxub8IVZcAlB7nadG4FRka2hfkhFh79ifk=','swbox1203655088','J')">J08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655088" onclick="onClickSelect(this,1203655088,'JpEiEbp/syaRtnGx/J8wAcdf4BcyG09BuhVcRrqqvT8=','swbox1203655088','J')">J08</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655017" onclick="onClickSelect(this,1203655017,'6HAYe3W5FK1whkie1he9tjCqY8vyIzPbq4/w+OkYwLk=','swbox1203655017','J')">J09</p>
      <p style={{margin: 3, width: 35, height: 35, background: 'url(/content/img/seat-sw.png)', backgroundSize: 'contain', color: '#333', textAlign: 'center', float: 'left', fontSize: '0.6rem', lineHeight: 35, letterSpacing: '0.5px', cursor: 'pointer'}} className="swbox1203655017" onclick="onClickSelect(this,1203655017,'YCd+otZripSYIWEBwyLl6L4dpwshDJl44VVNTX3hR1M=','swbox1203655017','J')">J09</p>
    </div>
  </div>
</div>

  );
}
